import { ComponentInstance } from './types';

export const INITIAL_COMPONENTS: ComponentInstance[] = [
  {
    id: 'hum-1',
    type: 'humidity_sensor',
    name: 'Humidity Prototype',
    port: 'P0',
    value: 45,
    x: 14,
    y: 22,
  },
  {
    id: 'light-1',
    type: 'light_sensor',
    name: 'Light Sensor',
    port: 'P1',
    value: 250,
    x: 28,
    y: 35,
  },
  {
    id: 'ultra-1',
    type: 'ultrasonic_sensor',
    name: 'Distance Sensor',
    port: 'P2',
    value: 120,
    x: 14,
    y: 55,
  },
  {
    id: 'pot-1',
    type: 'potentiometer',
    name: 'Rotary Dial',
    port: 'P3',
    value: 512,
    x: 28,
    y: 75,
  },
  {
    id: 'led-red',
    type: 'red_led',
    name: 'Alert LED',
    port: 'P4',
    value: 0,
    x: 72,
    y: 20,
  },
  {
    id: 'led-yellow',
    type: 'yellow_led',
    name: 'Status LED',
    port: 'P5',
    value: 0,
    x: 88,
    y: 20,
  },
  {
    id: 'motor-1',
    type: 'motor',
    name: 'DC Motor Fan',
    port: 'P6',
    value: 0,
    x: 72,
    y: 80,
  },
  {
    id: 'servo-1',
    type: 'servo',
    name: 'Micro Servo',
    port: 'P7',
    value: 90,
    x: 88,
    y: 80,
  },
  {
    id: 'btn-1',
    type: 'button',
    name: 'Push Button',
    port: 'P8',
    value: 0,
    x: 14,
    y: 90,
  },
  {
    id: 'buzzer-1',
    type: 'buzzer',
    name: 'Main Buzzer',
    port: 'P0',
    value: 0,
    x: 88,
    y: 50,
  }
];
